name: Django CI

on:
  push:
    branches: 
      - "main"  # Asegúrate de que la rama sea correcta
  pull_request:
    branches:
      - "main"  # Asegúrate de que el pull request también sea en la rama correcta

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations (if needed)
      run: |
        python manage.py migrate

    - name: Set up display for headless mode (if needed)
      run: |
        export DISPLAY=:99

    - name: Run Tests
      run: |
        python manage.py test
